In [13]:
l = [1,2,3,4]
import numpy as np
l2 = np.array([1,2,3,4])
l2[l2 > 2] #list comprehension np

array([3, 4])

In [16]:
l2[::2] #np array with step function
l3 = np.array([[1,2,3],[4,5,6]])
l3[:, ::2]
l3[-1, ::2] #step function, last row of 2d array

array([4, 6])

In [21]:
#python numpy reshape
l3.reshape(3,2)
l3.reshape(2,3)
l3.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [32]:
#numpy matrix, identify, zeros, ones, eyes
np.zeros((2,3))
np.ones((2,3))
np.diag((3,4,5))
np.eye(4) #identity

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [35]:
a = np.array([1,2,3])
b = np.array([1,2,4])
a.dot(b)

17

In [49]:
#type and casting
x = 1
a.dtype
c = a
#c.dtype
c = c.astype('f') #casting
c.dtype

dtype('float32')

In [56]:
#index of max or min, use argmax argmin
a = np.array([1,2,3,4,5,8,7,0,1,2])
a.max()
a.min()
a.argmax() #only available for numpy array
a.argmin()

7

In [59]:
a[::-2] #step size backwards by 2

array([2, 0, 8, 4, 2])